import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

const PRICE_ALERTS_BOOTSTRAP_PATH = resolve(
  process.cwd(),
  "supabase/bootstrap/00000000000000_create_price_alert_prerequisites.sql"
);
const PRICE_ALERTS_BOOTSTRAP_README_PATH = resolve(
  process.cwd(),
  "supabase/bootstrap/README.md"
);
const PRICE_ALERT_CONFIRMATION_MIGRATION_PATH = resolve(
  process.cwd(),
  "supabase/migrations/20260827000000_add_price_alert_confirmation_requested_at.sql"
);
const PRICE_ALERT_DELIVERY_MIGRATION_PATH = resolve(
  process.cwd(),
  "supabase/migrations/20260828000000_add_price_alert_target_delivery_state.sql"
);
const PRICE_ALERTS_HARDENING_MIGRATION_PATH = resolve(
  process.cwd(),
  "supabase/migrations/20260902010000_harden_price_alerts_rls.sql"
);
const DEFAULT_PRIVILEGES_MIGRATION_PATH = resolve(
  process.cwd(),
  "supabase/migrations/20260906000000_harden_public_default_privileges.sql"
);
const LATEST_CHECKS_MIGRATION_PATH = resolve(
  process.cwd(),
  "supabase/migrations/20260906010000_create_price_alert_latest_checks_rpc.sql"
);

function loadPriceAlertsBootstrap(): string {
  return readFileSync(PRICE_ALERTS_BOOTSTRAP_PATH, "utf8");
}

test("il bootstrap price_alerts e separato dalla migration chain e fallisce chiuso", () => {
  const sql = loadPriceAlertsBootstrap();
  const migrationFiles = readdirSync(
    resolve(process.cwd(), "supabase/migrations")
  );

  assert.match(sql, /^begin;/i);
  assert.match(sql, /commit;\s*$/i);
  assert.match(
    sql,
    /if current_user <> 'postgres' then[\s\S]*raise exception/i
  );
  assert.match(
    sql,
    /if to_regclass\('public\.price_alerts'\) is not null then[\s\S]*raise exception/i
  );
  assert.match(sql, /create table public\.price_alerts\s*\(/i);
  assert.equal(
    migrationFiles.includes(
      "00000000000000_create_price_alert_prerequisites.sql"
    ),
    false
  );
});

test("il bootstrap crea lo schema price_alerts pre-20260827 certificato", () => {
  const sql = loadPriceAlertsBootstrap();
  const createTableMatch = sql.match(
    /create table public\.price_alerts\s*\(([\s\S]*?)\);/i
  );

  assert.ok(createTableMatch);

  const tableDefinitions = createTableMatch[1]
    .split(",")
    .map((definition) => definition.trim());
  const columnNames = tableDefinitions
    .filter((definition) => !definition.startsWith("constraint "))
    .map((definition) => definition.match(/^([a-z_]+)/i)?.[1]);

  assert.deepEqual(columnNames, [
    "id",
    "created_at",
    "product_id",
    "product_title",
    "email",
    "target_price",
    "current_price",
    "status",
    "notified_at",
    "manage_token_hash",
    "intermediate_notified_at",
  ]);
  assert.equal(
    tableDefinitions.filter((definition) =>
      definition.startsWith("constraint ")
    ).length,
    1
  );

  for (const definition of [
    /id bigint generated by default as identity/i,
    /created_at timestamptz not null default now\(\)/i,
    /product_id text/i,
    /product_title text/i,
    /email text/i,
    /target_price numeric/i,
    /current_price numeric/i,
    /status text default 'active'::text/i,
    /notified_at timestamptz/i,
    /manage_token_hash text/i,
    /intermediate_notified_at timestamptz/i,
  ]) {
    assert.match(sql, definition);
  }

  assert.match(
    sql,
    /constraint price_alerts_pkey primary key \(id\)/i
  );
  assert.match(
    sql,
    /create unique index price_alerts_unique_exact_alert_idx\s+on public\.price_alerts using btree \(product_id, email, target_price\)/i
  );
  assert.match(
    sql,
    /revoke all privileges on sequence public\.price_alerts_id_seq/i
  );
});

test("il bootstrap non anticipa le quattro colonne aggiunte dalle migration", () => {
  const sql = loadPriceAlertsBootstrap();

  for (const laterColumn of [
    "confirmation_requested_at",
    "target_notification_claimed_at",
    "target_reached_at",
    "target_reached_price",
  ]) {
    assert.doesNotMatch(sql, new RegExp(`\\b${laterColumn}\\b`, "i"));
  }
});

test("il bootstrap revoca gli accessi pubblici senza duplicare l'hardening", () => {
  const sql = loadPriceAlertsBootstrap();

  assert.match(
    sql,
    /revoke all privileges on table public\.price_alerts\s+from public, anon, authenticated/i
  );
  assert.match(
    sql,
    /revoke all privileges on sequence public\.price_alerts_id_seq\s+from public, anon, authenticated/i
  );
  assert.doesNotMatch(sql, /\bgrant\b/i);
  assert.doesNotMatch(sql, /enable row level security/i);
  assert.doesNotMatch(sql, /create\s+policy/i);
  assert.doesNotMatch(sql, /alter default privileges/i);
});

test("il bootstrap resta compatibile con le migration price_alerts successive", () => {
  const bootstrap = loadPriceAlertsBootstrap();
  const confirmationMigration = readFileSync(
    PRICE_ALERT_CONFIRMATION_MIGRATION_PATH,
    "utf8"
  );
  const deliveryMigration = readFileSync(
    PRICE_ALERT_DELIVERY_MIGRATION_PATH,
    "utf8"
  );
  const hardeningMigration = readFileSync(
    PRICE_ALERTS_HARDENING_MIGRATION_PATH,
    "utf8"
  );
  const defaultPrivilegesMigration = readFileSync(
    DEFAULT_PRIVILEGES_MIGRATION_PATH,
    "utf8"
  );
  const latestChecksMigration = readFileSync(
    LATEST_CHECKS_MIGRATION_PATH,
    "utf8"
  );

  assert.match(
    confirmationMigration,
    /add column confirmation_requested_at timestamptz/i
  );
  assert.match(
    deliveryMigration,
    /add column target_notification_claimed_at timestamptz,[\s\S]*add column target_reached_at timestamptz,[\s\S]*add column target_reached_price numeric/i
  );
  assert.match(bootstrap, /generated by default as identity/i);
  assert.match(bootstrap, /price_alerts_unique_exact_alert_idx/i);
  assert.match(
    hardeningMigration,
    /alter table public\.price_alerts enable row level security/i
  );
  assert.match(defaultPrivilegesMigration, /alter default privileges/i);
  assert.match(
    latestChecksMigration,
    /create function public\.affario_price_alert_latest_product_checks/i
  );
  assert.doesNotMatch(bootstrap, /alter default privileges/i);
  assert.doesNotMatch(
    bootstrap,
    /affario_price_alert_latest_product_checks/i
  );
});

test("price_history resta fuori dal bootstrap V1 e nel perimetro backup Production", () => {
  const sql = loadPriceAlertsBootstrap();
  const readme = readFileSync(PRICE_ALERTS_BOOTSTRAP_README_PATH, "utf8");

  assert.doesNotMatch(sql, /\bprice_history\b/i);
  assert.match(readme, /price_history[\s\S]*esiste in Production/i);
  assert.match(readme, /intenzionalmente esclusa dal\s+bootstrap/i);
  assert.match(readme, /non sostituisce un backup e restore completo/i);
  assert.match(readme, /bootstrap[\s\S]*migration\s+chain V1/i);
  assert.match(readme, /NON eseguire contro Production esistente/);
  assert.match(
    readme,
    /20260820000000_create_keepa_storage\.sql[\s\S]*20260906010000_create_price_alert_latest_checks_rpc\.sql/i
  );
});

test("bootstrap e documentazione non contengono secret o endpoint specifici", () => {
  const content = `${loadPriceAlertsBootstrap()}\n${readFileSync(
    PRICE_ALERTS_BOOTSTRAP_README_PATH,
    "utf8"
  )}`;

  assert.doesNotMatch(content, /postgres(?:ql)?:\/\//i);
  assert.doesNotMatch(content, /https:\/\/[a-z0-9-]+\.supabase\.co/i);
  assert.doesNotMatch(
    content,
    /SUPABASE_(?:URL|ANON_KEY|SERVICE_ROLE_KEY)/i
  );
  assert.doesNotMatch(content, /\beyJ[A-Za-z0-9_-]{20,}\b/);
});
