begin;

create or replace function public.affario_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.products (
  asin text primary key,
  amazon_domain smallint not null,
  parent_asin text,
  title text not null,
  brand text,
  model text,
  color text,
  size text,
  image_url text,
  root_category bigint,
  category_ids bigint[],
  category_tree jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_asin_format_check
    check (asin ~ '^[A-Z0-9]{10}$'),
  constraint products_amazon_domain_check
    check (amazon_domain > 0),
  constraint products_parent_asin_format_check
    check (parent_asin is null or parent_asin ~ '^[A-Z0-9]{10}$'),
  constraint products_title_check
    check (btrim(title) <> ''),
  constraint products_root_category_check
    check (root_category is null or root_category > 0),
  constraint products_category_tree_check
    check (category_tree is null or jsonb_typeof(category_tree) = 'array'),
  constraint products_seen_at_check
    check (last_seen_at >= first_seen_at)
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  child_asin text not null references public.products (asin) on delete cascade,
  parent_asin text not null,
  attribute_dimension text not null,
  attribute_value text not null,
  related_asin text,
  observed_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_variants_parent_asin_format_check
    check (parent_asin ~ '^[A-Z0-9]{10}$'),
  constraint product_variants_related_asin_format_check
    check (related_asin is null or related_asin ~ '^[A-Z0-9]{10}$'),
  constraint product_variants_dimension_check
    check (btrim(attribute_dimension) <> ''),
  constraint product_variants_value_check
    check (btrim(attribute_value) <> '')
);

create table if not exists public.buybox_price_history (
  asin text not null references public.products (asin) on delete cascade,
  keepa_time integer not null,
  observed_at timestamptz not null,
  buybox_price_cents integer,
  shipping_cents integer,
  total_cents integer,
  currency text not null default 'EUR',
  created_at timestamptz not null default now(),
  primary key (asin, keepa_time),
  constraint buybox_price_history_keepa_time_check
    check (keepa_time >= 0),
  constraint buybox_price_history_price_check
    check (buybox_price_cents is null or buybox_price_cents >= 0),
  constraint buybox_price_history_shipping_check
    check (shipping_cents is null or shipping_cents >= 0),
  constraint buybox_price_history_total_check
    check (total_cents is null or total_cents >= 0),
  constraint buybox_price_history_total_consistency_check
    check (
      total_cents is null
      or (
        buybox_price_cents is not null
        and shipping_cents is not null
        and total_cents = buybox_price_cents + shipping_cents
      )
    ),
  constraint buybox_price_history_currency_check
    check (currency ~ '^[A-Z]{3}$')
);

create table if not exists public.keepa_snapshots (
  id bigint generated by default as identity primary key,
  asin text not null references public.products (asin) on delete cascade,
  requested_at timestamptz not null,
  last_buy_box_update_keepa_time integer,
  last_buy_box_updated_at timestamptz,
  buybox_current_cents integer,
  buybox_price_cents integer,
  buybox_shipping_cents integer,
  buybox_total_cents integer,
  currency text not null default 'EUR',
  buybox_seller_id text,
  buybox_is_amazon boolean,
  buybox_is_fba boolean,
  buybox_is_prime_eligible boolean,
  buybox_is_prime_exclusive boolean,
  buybox_is_shippable boolean,
  buybox_is_preorder boolean,
  buybox_is_backorder boolean,
  buybox_availability_message text,
  avg30_cents integer,
  avg90_cents integer,
  avg180_cents integer,
  avg365_cents integer,
  min90_cents integer,
  min90_keepa_time integer,
  min90_observed_at timestamptz,
  max90_cents integer,
  max90_keepa_time integer,
  max90_observed_at timestamptz,
  min_all_time_cents integer,
  min_all_time_keepa_time integer,
  min_all_time_observed_at timestamptz,
  max_all_time_cents integer,
  max_all_time_keepa_time integer,
  max_all_time_observed_at timestamptz,
  out_of_stock_percentage30 smallint,
  out_of_stock_percentage90 smallint,
  out_of_stock_percentage180 smallint,
  out_of_stock_percentage365 smallint,
  tokens_consumed smallint,
  created_at timestamptz not null default now(),
  constraint keepa_snapshots_asin_requested_at_key
    unique (asin, requested_at),
  constraint keepa_snapshots_last_buy_box_update_check
    check (
      last_buy_box_update_keepa_time is null
      or last_buy_box_update_keepa_time >= 0
    ),
  constraint keepa_snapshots_currency_check
    check (currency ~ '^[A-Z]{3}$'),
  constraint keepa_snapshots_money_check
    check (
      (buybox_current_cents is null or buybox_current_cents >= 0)
      and (buybox_price_cents is null or buybox_price_cents >= 0)
      and (buybox_shipping_cents is null or buybox_shipping_cents >= 0)
      and (buybox_total_cents is null or buybox_total_cents >= 0)
      and (avg30_cents is null or avg30_cents >= 0)
      and (avg90_cents is null or avg90_cents >= 0)
      and (avg180_cents is null or avg180_cents >= 0)
      and (avg365_cents is null or avg365_cents >= 0)
      and (min90_cents is null or min90_cents >= 0)
      and (max90_cents is null or max90_cents >= 0)
      and (min_all_time_cents is null or min_all_time_cents >= 0)
      and (max_all_time_cents is null or max_all_time_cents >= 0)
    ),
  constraint keepa_snapshots_buybox_total_consistency_check
    check (
      buybox_total_cents is null
      or (
        buybox_price_cents is not null
        and buybox_shipping_cents is not null
        and buybox_total_cents = buybox_price_cents + buybox_shipping_cents
      )
    ),
  constraint keepa_snapshots_extreme_times_check
    check (
      (min90_keepa_time is null or min90_keepa_time >= 0)
      and (max90_keepa_time is null or max90_keepa_time >= 0)
      and (
        min_all_time_keepa_time is null
        or min_all_time_keepa_time >= 0
      )
      and (
        max_all_time_keepa_time is null
        or max_all_time_keepa_time >= 0
      )
    ),
  constraint keepa_snapshots_out_of_stock_check
    check (
      (
        out_of_stock_percentage30 is null
        or out_of_stock_percentage30 between 0 and 100
      )
      and (
        out_of_stock_percentage90 is null
        or out_of_stock_percentage90 between 0 and 100
      )
      and (
        out_of_stock_percentage180 is null
        or out_of_stock_percentage180 between 0 and 100
      )
      and (
        out_of_stock_percentage365 is null
        or out_of_stock_percentage365 between 0 and 100
      )
    ),
  constraint keepa_snapshots_tokens_consumed_check
    check (tokens_consumed is null or tokens_consumed >= 0)
);

create table if not exists public.keepa_history_points (
  id bigint generated by default as identity primary key,
  asin text not null references public.products (asin) on delete cascade,
  data_type text not null,
  keepa_time integer not null,
  observed_at timestamptz not null,
  numeric_value numeric,
  text_value text,
  metadata jsonb not null default '{}'::jsonb,
  deduplication_key text not null default '',
  created_at timestamptz not null default now(),
  constraint keepa_history_points_identity_key
    unique (asin, data_type, keepa_time, deduplication_key),
  constraint keepa_history_points_data_type_check
    check (data_type ~ '^[A-Z0-9_]+$'),
  constraint keepa_history_points_keepa_time_check
    check (keepa_time >= 0),
  constraint keepa_history_points_metadata_check
    check (jsonb_typeof(metadata) = 'object'),
  constraint keepa_history_points_value_check
    check (
      numeric_value is not null
      or text_value is not null
      or metadata <> '{}'::jsonb
    )
);

create table if not exists public.keepa_raw_latest (
  asin text primary key references public.products (asin) on delete cascade,
  product_object jsonb not null,
  requested_at timestamptz not null,
  last_buy_box_update_keepa_time integer,
  last_buy_box_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint keepa_raw_latest_product_object_check
    check (jsonb_typeof(product_object) = 'object'),
  constraint keepa_raw_latest_last_buy_box_update_check
    check (
      last_buy_box_update_keepa_time is null
      or last_buy_box_update_keepa_time >= 0
    )
);

create unique index if not exists product_variants_identity_idx
  on public.product_variants (
    child_asin,
    parent_asin,
    attribute_dimension,
    attribute_value,
    (coalesce(related_asin, ''))
  );

create index if not exists products_parent_asin_idx
  on public.products (parent_asin)
  where parent_asin is not null;

create index if not exists product_variants_parent_asin_idx
  on public.product_variants (parent_asin);

create index if not exists buybox_price_history_asin_observed_at_idx
  on public.buybox_price_history (asin, observed_at desc);

create index if not exists keepa_history_points_asin_type_observed_at_idx
  on public.keepa_history_points (asin, data_type, observed_at desc);

drop trigger if exists products_set_updated_at
  on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.affario_set_updated_at();

drop trigger if exists product_variants_set_updated_at
  on public.product_variants;
create trigger product_variants_set_updated_at
before update on public.product_variants
for each row execute function public.affario_set_updated_at();

drop trigger if exists keepa_raw_latest_set_updated_at
  on public.keepa_raw_latest;
create trigger keepa_raw_latest_set_updated_at
before update on public.keepa_raw_latest
for each row execute function public.affario_set_updated_at();

alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.buybox_price_history enable row level security;
alter table public.keepa_snapshots enable row level security;
alter table public.keepa_history_points enable row level security;
alter table public.keepa_raw_latest enable row level security;

revoke all on table public.products from anon, authenticated;
revoke all on table public.product_variants from anon, authenticated;
revoke all on table public.buybox_price_history from anon, authenticated;
revoke all on table public.keepa_snapshots from anon, authenticated;
revoke all on table public.keepa_history_points from anon, authenticated;
revoke all on table public.keepa_raw_latest from anon, authenticated;

grant select, insert, update, delete on table public.products to service_role;
grant select, insert, update, delete on table public.product_variants to service_role;
grant select, insert, update, delete on table public.buybox_price_history to service_role;
grant select, insert, update, delete on table public.keepa_snapshots to service_role;
grant select, insert, update, delete on table public.keepa_history_points to service_role;
grant select, insert, update, delete on table public.keepa_raw_latest to service_role;

revoke all on sequence public.product_variants_id_seq from anon, authenticated;
revoke all on sequence public.keepa_snapshots_id_seq from anon, authenticated;
revoke all on sequence public.keepa_history_points_id_seq from anon, authenticated;

grant usage, select on sequence public.product_variants_id_seq to service_role;
grant usage, select on sequence public.keepa_snapshots_id_seq to service_role;
grant usage, select on sequence public.keepa_history_points_id_seq to service_role;

revoke execute on function public.affario_set_updated_at()
  from public, anon, authenticated;

comment on table public.products is
  'Anagrafica Amazon/Keepa: una sola riga per ASIN.';
comment on table public.product_variants is
  'Attributi che collegano un ASIN prodotto alla relativa famiglia Amazon.';
comment on table public.buybox_price_history is
  'Serie storica deduplicata Keepa BUY_BOX_SHIPPING (Price Type 18).';
comment on table public.keepa_snapshots is
  'Snapshot economico prodotto da una reale richiesta Keepa.';
comment on table public.keepa_history_points is
  'Storici Keepa flessibili non ancora promossi a tabelle specializzate.';
comment on column public.keepa_history_points.deduplication_key is
  'Dimensione stabile aggiuntiva, ad esempio category ID; stringa vuota quando non necessaria.';
comment on table public.keepa_raw_latest is
  'Ultimo Product Object Keepa completo, sostituito tramite upsert su ASIN.';

commit;
