begin;

do $bootstrap$
begin
  if current_user <> 'postgres' then
    raise exception
      'Bootstrap refused: it must run as postgres';
  end if;

  if to_regclass('public.price_alerts') is not null then
    raise exception
      'Bootstrap refused: public.price_alerts already exists';
  end if;
end;
$bootstrap$;

create table public.price_alerts (
  id bigint generated by default as identity,
  created_at timestamptz not null default now(),
  product_id text,
  product_title text,
  email text,
  target_price numeric,
  current_price numeric,
  status text default 'active'::text,
  notified_at timestamptz,
  manage_token_hash text,
  intermediate_notified_at timestamptz,
  constraint price_alerts_pkey primary key (id)
);

create unique index price_alerts_unique_exact_alert_idx
  on public.price_alerts using btree (product_id, email, target_price);

revoke all privileges on table public.price_alerts
  from public, anon, authenticated;
revoke all privileges on sequence public.price_alerts_id_seq
  from public, anon, authenticated;

commit;
